<?php

declare(strict_types=1);

namespace FormFlow;

/**
 * Writes config.php from installer-collected values.
 */
class ConfigWriter
{
  /**
   * @param array<string, mixed> $data
   */
  public static function write(string $rootPath, array $data): bool
  {
    $path = $rootPath . '/config.php';

    $app = $data['app'] ?? [];
    $database = $data['database'] ?? [];
    $smtp = $data['smtp'] ?? [];

    $config = [
      'app' => [
        'name' => (string) ($app['name'] ?? 'FormFlow'),
        'url' => rtrim((string) ($app['url'] ?? ''), '/'),
        'secret' => (string) ($app['secret'] ?? base64_encode(random_bytes(32))),
        'env' => (string) ($app['env'] ?? 'production'),
        'debug' => (bool) ($app['debug'] ?? false),
        'session_secure' => (bool) ($app['session_secure'] ?? true),
        'timezone' => (string) ($app['timezone'] ?? 'UTC'),
        'locale' => (string) ($app['locale'] ?? 'en'),
        'date_format' => (string) ($app['date_format'] ?? 'Y-m-d'),
      ],
      'database' => [
        'host' => (string) ($database['host'] ?? '127.0.0.1'),
        'port' => (int) ($database['port'] ?? 3306),
        'name' => (string) ($database['name'] ?? ''),
        'user' => (string) ($database['user'] ?? ''),
        'password' => (string) ($database['password'] ?? ''),
        'charset' => (string) ($database['charset'] ?? 'utf8mb4'),
        'prefix' => (string) ($database['prefix'] ?? ''),
      ],
      'smtp' => [
        'host' => (string) ($smtp['host'] ?? ''),
        'port' => (int) ($smtp['port'] ?? 587),
        'username' => (string) ($smtp['username'] ?? ''),
        'password' => (string) ($smtp['password'] ?? ''),
        'encryption' => (string) ($smtp['encryption'] ?? 'tls'),
        'from_email' => (string) ($smtp['from_email'] ?? ''),
        'from_name' => (string) ($smtp['from_name'] ?? ($app['name'] ?? 'FormFlow')),
      ],
      'security' => is_array($data['security'] ?? null) ? $data['security'] : ConfigManager::defaultSecurity(),
    ];

    $content = "<?php\n\ndeclare(strict_types=1);\n\n";
    $content .= "/**\n * FormFlow configuration — generated by the installer.\n";
    $content .= " * Do not commit this file.\n */\n\n";
    $content .= 'return ' . self::export($config) . ";\n";

    return file_put_contents($path, $content) !== false;
  }

  /**
   * @param mixed $value
   */
  private static function export($value): string
  {
    if (is_array($value)) {
      if ($value === []) {
        return '[]';
      }

      $isList = array_keys($value) === range(0, count($value) - 1);
      $parts = [];

      foreach ($value as $key => $item) {
        $exported = self::export($item);
        $parts[] = $isList ? $exported : var_export((string) $key, true) . ' => ' . $exported;
      }

      return '[' . "\n        " . implode(",\n        ", $parts) . ",\n    " . ']';
    }

    return var_export($value, true);
  }
}
